# Wards Main configuration. Version 1.0.4
# Created by Divios
# =========================================================
# Fields Explanation:
#   <chunk_display_seconds>:
#       - Amount of seconds the ward structure is displayed.
# ============================
#   <chunk_display_cooldown>:
#       - Amount of seconds until a player can request a ward display again.
# ============================
#     Although all the operations are done async and have great performance,
#     if exploited, it can cause some lag. Tweak this value depending on your player
#     base and server but 30 seconds should be fine
# ============================
#   <ward_check_cycle_seconds>:
#       - How often in ticks a ward checks in his given radius for players.
# ============================
#     This task is really optimized and done async. 20 ticks (1 sec) is a conservative value
#     that should work perfectly in most of the cases but don't be afraid to lower it.
# ============================
#   <ward_teleport_delay>:
#       - Ticks to wait until a player is teleported. If the player moves in the given time, the teleport is cancelled.
# ============================
# You must restart for changes to take affect when editing this file!
# =========================================================
chunk_display_seconds: 10
chunk_display_cooldown: 30
ward_check_cycle_seconds: 20
ward_teleport_delay: 0

